name = "AnalyticPulses"
uuid = "eb27ae5b-ba0a-4633-8ae7-339e2c8a5cc6"
authors = ["Kyle Sherbert <kyle.sherbert@vt.edu> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
SpecialMatrices = "928aab9d-ef52-54ac-8ca1-acd7ca42c160"

[compat]
julia = "1"
